# Use the official Node.js 20 image
FROM node:20

# Create and set the working directory
WORKDIR /app

# Build arguments to accept environment variables during build
ARG PORT
ARG JWT_SECRET
ARG EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ARG VONAGE_API
ARG VONAGE_API_SECRET
ARG VONAGE_PHONE_NUMBER
ARG AUTH_URL
ARG AZURE_STORAGE_CONNECTION_STRING
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG NODE_ENV
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG DB_USER
ARG DB_PASS
ARG DB_NAME
ARG DB_HOST
ARG EMAIL_PASS_NEW

# Set environment variables within the container
ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV EMAIL=${EMAIL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
ENV VONAGE_API=${VONAGE_API}
ENV VONAGE_API_SECRET=${VONAGE_API_SECRET}
ENV VONAGE_PHONE_NUMBER=${VONAGE_PHONE_NUMBER}
ENV AUTH_URL=${AUTH_URL}
ENV AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
ENV ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
ENV REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
ENV NODE_ENV=${NODE_ENV}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV DB_USER=${DB_USER}
ENV DB_PASS=${DB_PASS}
ENV DB_NAME=${DB_NAME}
ENV DB_HOST=${DB_HOST}
ENV EMAIL_PASS_NEW=${EMAIL_PASS_NEW}

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Print the environment variables to verify they are set correctly
RUN echo "PORT=$PORT" \
    && echo "JWT_SECRET=$JWT_SECRET" \
    && echo "EMAIL=$EMAIL" \
    && echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" \
    && echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" \
    && echo "FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID" \
    && echo "FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET" \
    && echo "VONAGE_API=$VONAGE_API" \
    && echo "VONAGE_API_SECRET=$VONAGE_API_SECRET" \
    && echo "VONAGE_PHONE_NUMBER=$VONAGE_PHONE_NUMBER" \
    && echo "AUTH_URL=$AUTH_URL" \
    && echo "AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING" \
    && echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" \
    && echo "REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET" \
    && echo "NODE_ENV=$NODE_ENV" \
    && echo "REDIS_HOST=$REDIS_HOST" \
    && echo "REDIS_PORT=$REDIS_PORT" \
    && echo "REDIS_PASSWORD=$REDIS_PASSWORD" \
    && echo "DB_USER=$DB_USER" \
    && echo "DB_PASS=$DB_PASS" \
    && echo "DB_NAME=$DB_NAME" \
    && echo "DB_HOST=$DB_HOST" \
    && echo "EMAIL_PASS_NEW=$EMAIL_PASS_NEW"

# Expose the port the app runs on
EXPOSE 5000

# Start the application
CMD ["node", "index.js"]
